### PR TITLE
Theme freifunk: refresh by rebasing on OpenWrt2020-theme

### PR DESCRIPTION
**Pull request by SvenRoederer**
This renews the broken Freifunk-theme (https://github.com/freifunk/openwrt-packages/issues/24) by replacing it with the OpenWrt-2020 theme and backports some ideas from the old one.

I tested it some time locally and would like to merge soon.

### CODE REVIEW

**Comment by SvenRoederer** [comment]
merged in order to fix Issue #24

**Comment by SvenRoederer** [comment]
@pmelange in https://github.com/freifunk-berlin/firmware/pull/792#issuecomment-621157891 you mentioned a SVG version of the favicon. Where can it be found?

**Comment by pmelange** [comment]
http://download-master.berlin.freifunk.net/logo/

**Comment by SvenRoederer** [comment]
Seems not the correct source, as the linked files contian the "freifunk.net" text-footer. But seems that the already included "logo.svg" is the correct one.

**Pull request merged**
